"""05172024_fixtypo_sub_class

Revision ID: 19158b370af4
Revises: adfd7dfe116f
Create Date: 2024-05-17 11:26:49.309795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '19158b370af4'
down_revision: Union[str, None] = 'adfd7dfe116f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noa_ltc_change_order', sa.Column('land_ltc_subclass_old', sa.String(length=10), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('land_ltc_subclass_new', sa.String(length=10), nullable=True))
    op.drop_column('noa_ltc_change_order', 'land_ltc_sub_class_old')
    op.drop_column('noa_ltc_change_order', 'land_ltc_sub_class_new')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noa_ltc_change_order', sa.Column('land_ltc_sub_class_new', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('land_ltc_sub_class_old', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('noa_ltc_change_order', 'land_ltc_subclass_new')
    op.drop_column('noa_ltc_change_order', 'land_ltc_subclass_old')
    # ### end Alembic commands ###
