"""Add_columnrevisedquantity

Revision ID: 19c1fa7e133e
Revises: 8474952e70fc
Create Date: 2024-04-23 10:59:42.892166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c1fa7e133e'
down_revision: Union[str, None] = '8474952e70fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noa_ltc_change_order', sa.Column('revisedquantity', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noa_ltc_change_order', 'revisedquantity')
    # ### end Alembic commands ###
