"""Drop_columnrevisedquantity

Revision ID: 8474952e70fc
Revises: b9d424c5ef46
Create Date: 2024-04-23 10:57:39.923711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8474952e70fc'
down_revision: Union[str, None] = 'b9d424c5ef46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noa_ltc_change_order', 'revisedquantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noa_ltc_change_order', sa.Column('revisedquantity', mysql.VARCHAR(length=8), nullable=False))
    # ### end Alembic commands ###
