"""05172024_fix_column_length

Revision ID: 91b507cf0a8e
Revises: 19158b370af4
Create Date: 2024-05-17 11:30:07.092167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91b507cf0a8e'
down_revision: Union[str, None] = '19158b370af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('noa_ltc_change_order', 'assessment_type',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.String(length=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('noa_ltc_change_order', 'assessment_type',
               existing_type=sa.String(length=4),
               type_=mysql.VARCHAR(length=2),
               existing_nullable=True)
    # ### end Alembic commands ###
