"""05172030_add_reviewed

Revision ID: a128bf528c8f
Revises: c88a089ff0c2
Create Date: 2024-05-30 10:30:45.171188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a128bf528c8f'
down_revision: Union[str, None] = 'c88a089ff0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noa_ltc_change_order', sa.Column('reviewed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noa_ltc_change_order', 'reviewed')
    # ### end Alembic commands ###
