"""Create noa_ltc_change_order

Revision ID: b9d424c5ef46
Revises: 
Create Date: 2024-04-23 10:37:07.176334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d424c5ef46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noa_ltc_change_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.String(length=4), nullable=False),
    sa.Column('fips_code', sa.String(length=5), nullable=False),
    sa.Column('assessment_no', sa.String(length=20), nullable=False),
    sa.Column('id_com', sa.String(length=25), nullable=False),
    sa.Column('batch_no', sa.String(length=12), nullable=False),
    sa.Column('ltc_nbr_total', sa.String(length=20), nullable=False),
    sa.Column('batch_created', sa.String(length=22), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('batch_updated', sa.String(length=22), nullable=False),
    sa.Column('batch_submitted', sa.String(length=22), nullable=False),
    sa.Column('batch_approved', sa.String(length=22), nullable=False),
    sa.Column('batch_rejected', sa.String(length=22), nullable=False),
    sa.Column('reject_reason', sa.String(length=22), nullable=False),
    sa.Column('approved_by', sa.String(length=20), nullable=False),
    sa.Column('received_by', sa.String(length=20), nullable=False),
    sa.Column('batch_submitted_by', sa.String(length=20), nullable=False),
    sa.Column('co_detail_id', sa.String(length=25), nullable=False),
    sa.Column('fk_co_master', sa.String(length=15), nullable=False),
    sa.Column('status_cod', sa.String(length=10), nullable=False),
    sa.Column('status_date', sa.String(length=22), nullable=False),
    sa.Column('ltc_comment', sa.String(length=100), nullable=False),
    sa.Column('batch_item_no', sa.String(length=10), nullable=False),
    sa.Column('ward', sa.String(length=4), nullable=False),
    sa.Column('assessment_type', sa.String(length=2), nullable=False),
    sa.Column('taxpayer_name', sa.String(length=50), nullable=False),
    sa.Column('contact_name', sa.String(length=50), nullable=False),
    sa.Column('taxpayer_addr1', sa.String(length=40), nullable=False),
    sa.Column('taxpayer_addr2', sa.String(length=40), nullable=False),
    sa.Column('taxpayer_addr3', sa.String(length=40), nullable=False),
    sa.Column('tc_fee_pd', sa.String(length=1), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('chk_no', sa.String(length=20), nullable=False),
    sa.Column('chk_amt', sa.String(length=9), nullable=False),
    sa.Column('prop_desc', sa.String(length=255), nullable=False),
    sa.Column('parcel_add', sa.String(length=50), nullable=False),
    sa.Column('place_fips', sa.String(length=5), nullable=False),
    sa.Column('assessor_ref_no', sa.String(length=15), nullable=False),
    sa.Column('assessment_status', sa.String(length=2), nullable=False),
    sa.Column('homestead_exempt', sa.String(length=1), nullable=False),
    sa.Column('homestead_percent', sa.String(length=3), nullable=False),
    sa.Column('restoration_tax_expmt', sa.String(length=1), nullable=False),
    sa.Column('co_submitted_by', sa.String(length=20), nullable=False),
    sa.Column('id_cav', sa.String(length=25), nullable=False),
    sa.Column('changeordersdetailsid', sa.String(length=25), nullable=False),
    sa.Column('presentdescription', sa.String(length=30), nullable=False),
    sa.Column('presentexempt', sa.String(length=7), nullable=False),
    sa.Column('presenttotalassessed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('presenthomesteadcredit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('presenttaxpayershare', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('presentquantity', sa.String(length=8), nullable=False),
    sa.Column('presentunits', sa.String(length=255), nullable=False),
    sa.Column('reviseddescription', sa.String(length=50), nullable=False),
    sa.Column('revisedexempt', sa.String(length=7), nullable=False),
    sa.Column('revisedtotalassessed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revisedhomesteadcredit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revisedtaxpayershare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revisedunits', sa.String(length=1), nullable=False),
    sa.Column('revisedquantity', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noa_ltc_change_order')
    # ### end Alembic commands ###
