"""05172024_fixtypo

Revision ID: c0cf724ff9a5
Revises: 14abd921bcaf
Create Date: 2024-05-17 11:15:52.674418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c0cf724ff9a5'
down_revision: Union[str, None] = '14abd921bcaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noa_ltc_change_order', sa.Column('restoration_tax_exempt', sa.String(length=1), nullable=True))
    op.drop_column('noa_ltc_change_order', 'restoration_tax_exepmt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noa_ltc_change_order', sa.Column('restoration_tax_exepmt', mysql.VARCHAR(length=1), nullable=True))
    op.drop_column('noa_ltc_change_order', 'restoration_tax_exempt')
    # ### end Alembic commands ###
