"""05172024_fixtypo_subclass

Revision ID: e8ef7d6cf3ed
Revises: c0cf724ff9a5
Create Date: 2024-05-17 11:23:42.029482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e8ef7d6cf3ed'
down_revision: Union[str, None] = 'c0cf724ff9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noa_ltc_change_order', sa.Column('building_ltc_subclass_old', sa.String(length=10), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('building_ltc_subclass_new', sa.String(length=10), nullable=True))
    op.drop_column('noa_ltc_change_order', 'building_ltc_sub_class_new')
    op.drop_column('noa_ltc_change_order', 'building_ltc_sub_class_old')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noa_ltc_change_order', sa.Column('building_ltc_sub_class_old', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('building_ltc_sub_class_new', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('noa_ltc_change_order', 'building_ltc_subclass_new')
    op.drop_column('noa_ltc_change_order', 'building_ltc_subclass_old')
    # ### end Alembic commands ###
