"""05152024_add_auth_token_field

Revision ID: e948cba3d608
Revises: 8280295385b3
Create Date: 2024-05-16 09:03:38.467885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e948cba3d608'
down_revision: Union[str, None] = '8280295385b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noa_ltc_change_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_token', sa.String(length=32), nullable=True),
    sa.Column('tax_year', sa.String(length=4), nullable=True),
    sa.Column('fips_code', sa.String(length=5), nullable=True),
    sa.Column('assessment_no', sa.String(length=20), nullable=True),
    sa.Column('ward', sa.String(length=4), nullable=True),
    sa.Column('assessor_ref_no', sa.String(length=15), nullable=True),
    sa.Column('place_fips', sa.String(length=5), nullable=True),
    sa.Column('parcel_address', sa.String(length=50), nullable=True),
    sa.Column('assessment_type', sa.String(length=2), nullable=True),
    sa.Column('assessment_status', sa.String(length=2), nullable=True),
    sa.Column('homestead_exempt', sa.String(length=1), nullable=True),
    sa.Column('homestead_percent', sa.String(length=3), nullable=True),
    sa.Column('restoration_tax_exepmt', sa.String(length=1), nullable=True),
    sa.Column('taxpayer_name', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=50), nullable=True),
    sa.Column('taxpayer_addr1', sa.String(length=40), nullable=True),
    sa.Column('taxpayer_addr2', sa.String(length=40), nullable=True),
    sa.Column('taxpayer_addr3', sa.String(length=40), nullable=True),
    sa.Column('tc_fee_pd', sa.String(length=1), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('check_no', sa.String(length=20), nullable=True),
    sa.Column('check_amount', sa.String(length=9), nullable=True),
    sa.Column('batch_no', sa.String(length=12), nullable=True),
    sa.Column('ltc_nbr_total', sa.String(length=20), nullable=True),
    sa.Column('batch_created', sa.String(length=22), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('batch_updated', sa.String(length=22), nullable=True),
    sa.Column('batch_submitted', sa.String(length=22), nullable=True),
    sa.Column('batch_approved', sa.String(length=22), nullable=True),
    sa.Column('batch_rejected', sa.String(length=22), nullable=True),
    sa.Column('reject_reason', sa.String(length=22), nullable=True),
    sa.Column('approved_by', sa.String(length=20), nullable=True),
    sa.Column('received_by', sa.String(length=20), nullable=True),
    sa.Column('batch_submitted_by', sa.String(length=20), nullable=True),
    sa.Column('co_detail_id', sa.String(length=25), nullable=True),
    sa.Column('fk_co_master', sa.String(length=15), nullable=True),
    sa.Column('status_cod', sa.String(length=10), nullable=True),
    sa.Column('status_date', sa.String(length=22), nullable=True),
    sa.Column('ltc_comment', sa.String(length=100), nullable=True),
    sa.Column('batch_item_no', sa.String(length=10), nullable=True),
    sa.Column('prop_desc', sa.String(length=255), nullable=True),
    sa.Column('parcel_add', sa.String(length=50), nullable=True),
    sa.Column('co_submitted_by', sa.String(length=20), nullable=True),
    sa.Column('id_cav', sa.String(length=25), nullable=True),
    sa.Column('changeordersdetailsid', sa.String(length=25), nullable=True),
    sa.Column('presentdescription', sa.String(length=30), nullable=True),
    sa.Column('presentexempt', sa.String(length=7), nullable=True),
    sa.Column('presenttotalassessed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('presenthomesteadcredit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('presenttaxpayershare', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('presentquantity', sa.String(length=8), nullable=True),
    sa.Column('presentunits', sa.String(length=255), nullable=True),
    sa.Column('reviseddescription', sa.String(length=50), nullable=True),
    sa.Column('revisedexempt', sa.String(length=7), nullable=True),
    sa.Column('revisedtotalassessed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revisedhomesteadcredit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revisedtaxpayershare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revisedunits', sa.String(length=1), nullable=True),
    sa.Column('revisedquantity', sa.String(length=8), nullable=True),
    sa.Column('ltc_sub_class_old_land', sa.String(length=10), nullable=True),
    sa.Column('ltc_sub_class_new_land', sa.String(length=10), nullable=True),
    sa.Column('quantity_old_land', sa.Integer(), nullable=True),
    sa.Column('quantity_new_land', sa.Integer(), nullable=True),
    sa.Column('units_old_land', sa.String(length=1), nullable=True),
    sa.Column('units_new_land', sa.String(length=1), nullable=True),
    sa.Column('other_exempt_old_land', sa.Integer(), nullable=True),
    sa.Column('other_exempt_new_land', sa.Integer(), nullable=True),
    sa.Column('value_old_total_land', sa.Integer(), nullable=True),
    sa.Column('value_new_total_land', sa.Integer(), nullable=True),
    sa.Column('value_old_hs_land', sa.Integer(), nullable=True),
    sa.Column('value_new_hs_land', sa.Integer(), nullable=True),
    sa.Column('value_old_tp_land', sa.Integer(), nullable=True),
    sa.Column('value_new_tp_land', sa.Integer(), nullable=True),
    sa.Column('ltc_sub_class_old_building', sa.String(length=10), nullable=True),
    sa.Column('ltc_sub_class_new_building', sa.String(length=10), nullable=True),
    sa.Column('quantity_old_building', sa.Integer(), nullable=True),
    sa.Column('quantity_new_building', sa.Integer(), nullable=True),
    sa.Column('units_old_building', sa.String(length=1), nullable=True),
    sa.Column('units_new_building', sa.String(length=1), nullable=True),
    sa.Column('other_exempt_old_building', sa.Integer(), nullable=True),
    sa.Column('other_exempt_new_building', sa.Integer(), nullable=True),
    sa.Column('value_old_tota_building', sa.Integer(), nullable=True),
    sa.Column('value_new_total_building', sa.Integer(), nullable=True),
    sa.Column('value_old_hs_building', sa.Integer(), nullable=True),
    sa.Column('value_new_hs_building', sa.Integer(), nullable=True),
    sa.Column('value_old_tp_building', sa.Integer(), nullable=True),
    sa.Column('value_new_tp_building', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noa_ltc_change_order')
    # ### end Alembic commands ###
