"""alter_allow_nullable

Revision ID: f95b3a0779a9
Revises: 19c1fa7e133e
Create Date: 2024-04-24 15:37:02.669560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f95b3a0779a9'
down_revision: Union[str, None] = '19c1fa7e133e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('noa_ltc_change_order', 'tax_year',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'fips_code',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'assessment_no',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'id_com',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'batch_no',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'ltc_nbr_total',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'batch_created',
               existing_type=mysql.VARCHAR(length=22),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'status',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'batch_updated',
               existing_type=mysql.VARCHAR(length=22),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'batch_submitted',
               existing_type=mysql.VARCHAR(length=22),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'batch_approved',
               existing_type=mysql.VARCHAR(length=22),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'batch_rejected',
               existing_type=mysql.VARCHAR(length=22),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'reject_reason',
               existing_type=mysql.VARCHAR(length=22),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'approved_by',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'received_by',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'batch_submitted_by',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'co_detail_id',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'fk_co_master',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'status_cod',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'status_date',
               existing_type=mysql.VARCHAR(length=22),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'ltc_comment',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'batch_item_no',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'ward',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'assessment_type',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'taxpayer_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'contact_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'taxpayer_addr1',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'taxpayer_addr2',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'taxpayer_addr3',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'tc_fee_pd',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'reason',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'chk_no',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'chk_amt',
               existing_type=mysql.VARCHAR(length=9),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'prop_desc',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'parcel_add',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'place_fips',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'assessor_ref_no',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'assessment_status',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'homestead_exempt',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'homestead_percent',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'restoration_tax_expmt',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'co_submitted_by',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'id_cav',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'changeordersdetailsid',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'presentdescription',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'presentexempt',
               existing_type=mysql.VARCHAR(length=7),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'presentquantity',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'presentunits',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'reviseddescription',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'revisedexempt',
               existing_type=mysql.VARCHAR(length=7),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'revisedunits',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('noa_ltc_change_order', 'revisedquantity',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('noa_ltc_change_order', 'revisedquantity',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'revisedunits',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'revisedexempt',
               existing_type=mysql.VARCHAR(length=7),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'reviseddescription',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'presentunits',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'presentquantity',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'presentexempt',
               existing_type=mysql.VARCHAR(length=7),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'presentdescription',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'changeordersdetailsid',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'id_cav',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'co_submitted_by',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'restoration_tax_expmt',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'homestead_percent',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'homestead_exempt',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'assessment_status',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'assessor_ref_no',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'place_fips',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'parcel_add',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'prop_desc',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'chk_amt',
               existing_type=mysql.VARCHAR(length=9),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'chk_no',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'reason',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'tc_fee_pd',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'taxpayer_addr3',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'taxpayer_addr2',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'taxpayer_addr1',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'contact_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'taxpayer_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'assessment_type',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'ward',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'batch_item_no',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'ltc_comment',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'status_date',
               existing_type=mysql.VARCHAR(length=22),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'status_cod',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'fk_co_master',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'co_detail_id',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'batch_submitted_by',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'received_by',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'approved_by',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'reject_reason',
               existing_type=mysql.VARCHAR(length=22),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'batch_rejected',
               existing_type=mysql.VARCHAR(length=22),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'batch_approved',
               existing_type=mysql.VARCHAR(length=22),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'batch_submitted',
               existing_type=mysql.VARCHAR(length=22),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'batch_updated',
               existing_type=mysql.VARCHAR(length=22),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'status',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'batch_created',
               existing_type=mysql.VARCHAR(length=22),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'ltc_nbr_total',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'batch_no',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'id_com',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'assessment_no',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'fips_code',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('noa_ltc_change_order', 'tax_year',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)
    # ### end Alembic commands ###
