"""flatten into one table

Revision ID: f9e0c9e7218e
Revises: f1d616cd3ec7
Create Date: 2024-05-14 15:57:53.659366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f9e0c9e7218e'
down_revision: Union[str, None] = 'f1d616cd3ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noa_ltc_change_order_land')
    op.drop_table('noa_ltc_change_order_building')
    op.add_column('noa_ltc_change_order', sa.Column('ltc_sub_class_old_land', sa.String(length=10), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('ltc_sub_class_new_land', sa.String(length=10), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('quantity_old_land', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('quantity_new_land', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('units_old_land', sa.String(length=1), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('units_new_land', sa.String(length=1), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('other_exempt_old_land', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('other_exempt_new_land', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('value_old_total_land', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('value_new_total_land', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('value_old_hs_land', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('value_new_hs_land', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('value_old_tp_land', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('value_new_tp_land', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('ltc_sub_class_old_building', sa.String(length=10), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('ltc_sub_class_new_building', sa.String(length=10), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('quantity_old_building', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('quantity_new_building', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('units_old_building', sa.String(length=1), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('units_new_building', sa.String(length=1), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('other_exempt_old_building', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('other_exempt_new_building', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('value_old_tota_building', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('value_new_total_building', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('value_old_hs_building', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('value_new_hs_building', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('value_old_tp_building', sa.Integer(), nullable=True))
    op.add_column('noa_ltc_change_order', sa.Column('value_new_tp_building', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noa_ltc_change_order', 'value_new_tp_building')
    op.drop_column('noa_ltc_change_order', 'value_old_tp_building')
    op.drop_column('noa_ltc_change_order', 'value_new_hs_building')
    op.drop_column('noa_ltc_change_order', 'value_old_hs_building')
    op.drop_column('noa_ltc_change_order', 'value_new_total_building')
    op.drop_column('noa_ltc_change_order', 'value_old_tota_building')
    op.drop_column('noa_ltc_change_order', 'other_exempt_new_building')
    op.drop_column('noa_ltc_change_order', 'other_exempt_old_building')
    op.drop_column('noa_ltc_change_order', 'units_new_building')
    op.drop_column('noa_ltc_change_order', 'units_old_building')
    op.drop_column('noa_ltc_change_order', 'quantity_new_building')
    op.drop_column('noa_ltc_change_order', 'quantity_old_building')
    op.drop_column('noa_ltc_change_order', 'ltc_sub_class_new_building')
    op.drop_column('noa_ltc_change_order', 'ltc_sub_class_old_building')
    op.drop_column('noa_ltc_change_order', 'value_new_tp_land')
    op.drop_column('noa_ltc_change_order', 'value_old_tp_land')
    op.drop_column('noa_ltc_change_order', 'value_new_hs_land')
    op.drop_column('noa_ltc_change_order', 'value_old_hs_land')
    op.drop_column('noa_ltc_change_order', 'value_new_total_land')
    op.drop_column('noa_ltc_change_order', 'value_old_total_land')
    op.drop_column('noa_ltc_change_order', 'other_exempt_new_land')
    op.drop_column('noa_ltc_change_order', 'other_exempt_old_land')
    op.drop_column('noa_ltc_change_order', 'units_new_land')
    op.drop_column('noa_ltc_change_order', 'units_old_land')
    op.drop_column('noa_ltc_change_order', 'quantity_new_land')
    op.drop_column('noa_ltc_change_order', 'quantity_old_land')
    op.drop_column('noa_ltc_change_order', 'ltc_sub_class_new_land')
    op.drop_column('noa_ltc_change_order', 'ltc_sub_class_old_land')
    op.create_table('noa_ltc_change_order_building',
    sa.Column('ltc_sub_class_old', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('ltc_sub_class_new', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('quantity_old', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_new', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('units_old', mysql.VARCHAR(length=1), nullable=True),
    sa.Column('units_new', mysql.VARCHAR(length=1), nullable=True),
    sa.Column('other_exempt_old', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_exempt_new', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_old_total', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_new_total', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_old_hs', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_new_hs', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_old_tp', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_new_tp', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('noaltc_change_order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['noaltc_change_order_id'], ['noa_ltc_change_order.id'], name='noa_ltc_change_order_building_ibfk_1'),
    sa.PrimaryKeyConstraint('noaltc_change_order_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('noa_ltc_change_order_land',
    sa.Column('ltc_sub_class_old', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('ltc_sub_class_new', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('quantity_old', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_new', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('units_old', mysql.VARCHAR(length=1), nullable=True),
    sa.Column('units_new', mysql.VARCHAR(length=1), nullable=True),
    sa.Column('other_exempt_old', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_exempt_new', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_old_total', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_new_total', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_old_hs', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_new_hs', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_old_tp', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_new_tp', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('noaltc_change_order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['noaltc_change_order_id'], ['noa_ltc_change_order.id'], name='noa_ltc_change_order_land_ibfk_1'),
    sa.PrimaryKeyConstraint('noaltc_change_order_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
