INSERT INTO noa_ltc_change_order(
    batch_no ,
    batch_created ,
    status,
    batch_updated,        
    batch_submitted ,  
    batch_approved ,     
    batch_rejected ,  
    reviewed ,
    auth_token ,
    jur ,
    parid,
    saledt ,
    recorddt ,
    tax_year ,
    fips_code,
    assessment_no ,
    ward ,
    assessor_ref_no,
    fips_place_code,
    parcel_address ,
    assessment_type ,
    assessment_status ,
    homestead_exempt,
    homestead_percent ,
    restoration_tax_abatement ,
    taxpayer_name ,
    contact_name ,
    taxpayer_addr1 ,
    taxpayer_addr2, 
    taxpayer_addr3 ,
    tc_fee_pd ,
    reason,
    check_no ,
    check_amount ,
    reject_reason ,
    ltc_sub_class_old1 ,
    ltc_sub_class_new1 ,
    quantity_old1 ,
    quantity_new1,
    units_old1,
    units_new1,
    other_exempt_old1,
    other_exempt_new1,
    value_old_total1 ,
    value_new_total1,
    value_old_hs1 ,
    value_new_hs1,
    value_old_tp1 ,
    value_new_tp1,
    ltc_sub_class_old2,
    ltc_sub_class_new2,
    quantity_old2,
    quantity_new2,
    units_old2 ,
    units_new2 ,
    other_exempt_old2,
    other_exempt_new2,
    value_old_total2 ,
    value_new_total2 ,
    value_old_hs2 ,
    value_new_hs2 ,
    value_old_tp2,
    value_new_tp2 ,
    proper_desc
)
VALUES (:1,:2,:3,:4,:5,:6,:7,:8,:9,:10,:11,:12,
        :13,:14,:15,:16,:17,:18,:19,:20,:21,:22,
        :23,:24,:25,:26,:27,:28,:29,:30,:31,:32,
        :33,:34,:35,:36,:37,:38,:39,:40,:41,:42,
        :43,:44,:45,:46,:47,:48,:49:50,:51,:52,
        :53,:54,:55,:56, :57, :58, :59, :60,
        :61, :62, :63, :64
)
