from app import db
from werkzeug.security import generate_password_hash, check_password_hash
from secrets import token_urlsafe
from sqlalchemy import event
from datetime import datetime
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()



class NOALTCChangeOrder(Base):
    __tablename__ = "noa_ltc_change_order"

    id = db.Column(db.Integer(), primary_key=True)
    batch_no = db.Column(db.String(12), nullable=True)
    batch_created = db.Column(db.String(22), nullable=True)
    status = db.Column(db.String(10), nullable=True)
    batch_updated = db.Column(db.String(22), nullable=True)          
    batch_submitted = db.Column(db.String(22), nullable=True)       
    batch_approved  = db.Column(db.String(22), nullable=True)         
    batch_rejected = db.Column(db.String(22), nullable=True)        
    reviewed = db.Column(db.Boolean())
    auth_token = db.Column(db.String(256), nullable=True)
    jur = db.Column(db.String(4), nullable=True)
    parid = db.Column(db.String(12), nullable=True)
    saledt = db.Column(db.Date())
    recorddt = db.Column(db.Date())
    tax_year = db.Column(db.String(4), nullable=True)
    fips_code = db.Column(db.String(5), nullable=True)
    assessment_no = db.Column(db.String(20), nullable=True)
    ward = db.Column(db.String(4), nullable=True)
    assessor_ref_no = db.Column(db.String(15), nullable=True)
    fips_place_code = db.Column(db.String(5), nullable=True)
    parcel_address  = db.Column(db.String(50), nullable=True)
    assessment_type = db.Column(db.String(4), nullable=True)
    assessment_status = db.Column(db.String(2), nullable=True)
    homestead_exempt = db.Column(db.String(1), nullable=True)
    homestead_percent = db.Column(db.String(3), nullable=True)
    restoration_tax_abatement = db.Column(db.String(1), nullable=True)
    taxpayer_name  = db.Column(db.String(50), nullable=True)
    contact_name  = db.Column(db.String(50), nullable=True)
    taxpayer_addr1 = db.Column(db.String(40), nullable=True)         
    taxpayer_addr2 = db.Column(db.String(40), nullable=True)          
    taxpayer_addr3 = db.Column(db.String(40), nullable=True)    
    tc_fee_pd  = db.Column(db.String(1), nullable=True)  
    reason  = db.Column(db.String(255), nullable=True)   
    check_no  = db.Column(db.String(20), nullable=True)   
    check_amount = db.Column(db.String(9), nullable=True) 
    reject_reason = db.Column(db.String(22), nullable=True) 
    ltc_sub_class_old1 = db.Column(db.Integer, default=0)
    ltc_sub_class_new1  = db.Column(db.Integer, default=0)
    quantity_old1 = db.Column(db.Integer, default=0)
    quantity_new1 = db.Column(db.Integer, default=0)
    units_old1  = db.Column(db.String(2), nullable=True) 
    units_new1  = db.Column(db.String(2), nullable=True) 
    other_exempt_old1 = db.Column(db.Integer, default=0)
    other_exempt_new1 = db.Column(db.Integer, default=0)
    value_old_total1 = db.Column(db.Integer, default=0)
    value_new_total1 = db.Column(db.Integer, default=0)
    value_old_hs1 = db.Column(db.Integer, default=0)
    value_new_hs1 = db.Column(db.Integer, default=0)
    value_old_tp1 = db.Column(db.Integer, default=0)
    value_new_tp1 = db.Column(db.Integer, default=0)
    ltc_sub_class_old2 = db.Column(db.Integer, default=0)
    ltc_sub_class_new2 = db.Column(db.Integer, default=0)
    quantity_old2 = db.Column(db.Integer, default=0)
    quantity_new2 = db.Column(db.Integer, default=0)
    units_old2  = db.Column(db.String(2), nullable=True) 
    units_new2 = db.Column(db.String(2), nullable=True) 
    other_exempt_old2 = db.Column(db.Integer, default=0)
    other_exempt_new2 = db.Column(db.Integer, default=0)
    value_old_total2 = db.Column(db.Integer, default=0)
    value_new_total2 = db.Column(db.Integer, default=0)
    value_old_hs2 = db.Column(db.Integer, default=0)
    value_new_hs2 = db.Column(db.Integer, default=0)
    value_old_tp2 = db.Column(db.Integer, default=0)
    value_new_tp2 = db.Column(db.Integer, default=0)
    proper_desc = db.Column(db.String(300), nullable=True)

    